name: study_mentor_mobile
description: A new Flutter project.


publish_to: 'none' 













version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'







dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0

  
  
  cupertino_icons: ^1.0.2
  go_router: ^13.2.0
  flutter_svg: ^2.0.10+1
  flutter_switch: ^0.3.2
  dotted_border: ^2.1.0
  flutter_rating_bar: ^4.0.1
  dio: ^5.4.3+1
  file_picker: ^8.0.1
  provider: ^6.1.2
  socket_io_client: ^2.0.3+1
  image_picker: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  
  
  
  
  flutter_lints: ^2.0.0





flutter:

  
  
  
  uses-material-design: true

  
  assets:
    - assets/imgs/
    - assets/svgs/

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
