name: study_mentor_mobile
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  go_router: ^13.2.0
  flutter_svg: ^2.0.10+1
  flutter_switch: ^0.3.2
  dotted_border: ^2.1.0
  flutter_rating_bar: ^4.0.1
  dio: ^5.4.3+1
  file_picker: 7.1.0+1
  provider: ^6.1.2
  socket_io_client: ^2.0.3+1
  image_picker: ^1.1.1
  flutter_bloc: ^8.1.3
  nested: ^1.0.0
  equatable: ^2.0.5
  logger: ^2.0.2+1
  flutter_dotenv: ^5.1.0
  meta: ^1.10.0
  carousel_slider: ^4.2.1
  path_provider: ^2.1.1
  path: ^1.8.3
  auto_size_text: ^3.0.0
  firebase_core: ^2.24.2
  bloc: ^8.1.2
  flutter_pannable_rating_bar: ^2.7.2+1
  dart_mappable: ^4.2.1
  retrofit: ^4.1.0
  retrofit_generator: ^8.1.0
  dart_mappable_builder: ^4.2.1
  dotenv: ^4.2.0
  package_info_plus: ^5.0.1
  shared_preferences: ^2.2.2
  formz: ^0.7.0
  uni_links: ^0.5.1
  flutter_quill: ^9.3.0
  url_launcher: ^6.2.5
  flutter_keyboard_visibility: ^6.0.0
  device_info_plus: ^9.1.2
  # super_clipboard: ^0.8.5
  flutter_quill_extensions: ^9.3.0
  quill_html_converter: ^9.3.0
  image_cropper: ^5.0.1
  gal: ^2.3.0
  firebase_auth: ^4.16.0
  google_sign_in: ^6.2.1
  shimmer: ^3.0.0
  mime: ^1.0.5
  uuid: ^4.3.3
  sign_in_with_apple: ^6.0.0
  share_plus: ^7.2.2
  timeline_tile: ^2.0.0
  flutter_markdown: ^0.7.1
  firebase_messaging: ^14.7.6
  flutter_local_notifications: ^17.1.2
  open_file: ^3.3.2
  flutter_downloader: ^1.11.7
  flutter_holo_date_picker: ^1.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  flutter_gen_runner: ^5.3.2
  color_gen: ^0.1.3
  go_router_builder: ^2.4.1
  flutter_native_splash: ^2.3.10
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/fonts/
    - assets/svgs/
    - assets/images/
    - assets/images/home_logo/
    - assets/images/home_banner/
    - assets/images/home_banner_1/
    - assets/images/logo/
    - assets/images/icons/
    - shorebird.yaml

flutter_gen:
  output: lib/presentation/gen
  line_length: 80
  integrations:
    flutter_svg: true
# flutter_native_splash:
#   color: "#FFFFFF"
#   image: assets/images/splash_screen_native_logo/splash_screen_native_logo.png
#   android_12:
#     color: "#FFFFFF"
#     image: assets/images/splash_screen_native_logo/splash_screen_native_logo.png
#   web: false
#   fullscreen: false

# flutter_launcher_icons:
#   android: true
#   ios: true
#   remove_alpha_ios: true
#   image_path: "assets/images/launcher_logo/launcher_logo.png"
#   min_sdk_android: 21
