// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgMQLSVQH34Ol9vbcX1QPtUwFfsikhZGY',
    appId: '1:722720840680:android:9b5341e846c452dbfae25d',
    messagingSenderId: '722720840680',
    projectId: 'success-mania-86e8e',
    storageBucket: 'success-mania-86e8e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMdNlX-bV_35cIEJE_dQedXWKyfu9nnSk',
    appId: '1:722720840680:ios:3ed9c97eb13d5da6fae25d',
    messagingSenderId: '722720840680',
    projectId: 'success-mania-86e8e',
    storageBucket: 'success-mania-86e8e.appspot.com',
    androidClientId:
        '722720840680-674f4160gc6ifmrl90p91vf6960icsmo.apps.googleusercontent.com',
    iosClientId:
        '722720840680-6a4tfvj4fhfqg1hbf1o3p3a0v2nsijco.apps.googleusercontent.com',
    iosBundleId: 'com.successMania.successManiaMobile',
  );
}
